Patch CACTUS AMC13 Makefiles to work on Debian/Ubuntu
lpetre-ulb/gemsuperbuild pull request #9
Opened 2019-03-03 22:20 UTC by lmoureaux

The --as-needed linker flag (enabled by default on Ubuntu 18.04) breaks
compilation. Fix it by reordering -l flags.

Tested by doing the following:

```sh
$ rm -r thirdparty/cactus/amc13/
$ XDAQ_PLATFORM=x86_64 XDAQ_ROOT=$(readlink -f install/xdaq/x86_64/) make SHELL=/bin/bash
```

Compilation succeeds.

2019-03-03 22:27 UTC, lpetre-ulb requested changes
Although I have not tested the fix for the `--as-needed` flag, I cannot see any problem in the patch. It will be part of my next round of tests.

However, the `SHELL` issue doesn't seem addressed in this PR. Do you plan to address it in an other PR ? Can't the fix be part of this PR ?

2019-03-03 23:24 UTC, lpetre-ulb reviewed
If it has been tested on a clean build, I'll approve.

2019-03-03 23:24 UTC, lpetre-ulb commented on cmake/External_cactus.cmake
> +    "SHELL=bash"
Have you tried you your patch in a clean build ? I'm a bit surprised that you don't need to pass `"SHELL=bash"` to the `INSTALL_COMMAND`. Or maybe that the directories are already created by `cactus-ipbus` ?

2019-03-04 08:34 UTC, lmoureaux commented
Rebased, added asyncresolv patch, tested clean build.

Make commands used:
```sh
XDAQ_PLATFORM=x86_64 make # I'm afraid of setting XDAQ_ROOT when building xDAQ
XDAQ_PLATFORM=x86_64 XDAQ_ROOT=$(readlink -f install/xdaq/x86_64/) make
```

2019-03-04 09:59 UTC, lpetre-ulb approved these changes

2019-03-04 10:04 UTC, lpetre-ulb commented
Ok, thank you for addressing my concerns.

> ``` shell
> XDAQ_PLATFORM=x86_64 make # I'm afraid of setting XDAQ_ROOT when building xDAQ
> XDAQ_PLATFORM=x86_64 XDAQ_ROOT=$(readlink -f install/xdaq/x86_64/) make
> ```

You are right, setting `XDAQ_ROOT` during the build of `xDAQ` might failed the compilation.

2019-03-04 10:05 UTC, merged

2019-03-04 10:05 UTC, lpetre-ulb commented
Fixes #3.